esphome:
  name: pwc-demo
  platformio_options:
    upload_speed: 500000

esp32:
  board: m5stick-c
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  networks:
  - ssid: !secret wifi_name
    password: !secret wifi_password
  - ssid: !secret wifi_hotspot_name 
    password: !secret wifi_hotspot_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pwc-Demo Fallback Hotspot"
    password: "password123"

captive_portal:

binary_sensor:

  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: Demo Button A
    on_press:
      then:
        - light.toggle: led1

  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Demo Button B
    on_press:
      then:
        - light.toggle: led1
    

light:
  - platform: monochromatic 
    output:  builtin_led
    name: Demo Led
    id: led1

output:
  - platform: ledc
    pin: 10
    id: builtin_led
    inverted: true


sensor:
  - platform: uptime
    name: Uptime Sensor
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s